/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.go.bps.lampung.monitorentri.ui;

import id.go.bps.lampung.monitorentri.assets.ResourceImage;
import id.go.bps.lampung.monitorentri.assets.StringImage;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author ekoteguh
 */
public class MainFrame extends javax.swing.JFrame {

    int status = 0;
    String sensusSurveiId;
    boolean isLoggedIn = false;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        MainFrame.this.setSize(1024, 720);
        MainFrame.this.setLocationRelativeTo(null);
        MainFrame.this.setResizable(false);
        MainFrame.this.setLogged(this.isLoggedIn, 0, "");
    }
    
    public void setLogged(boolean isLoggedIn, int status, String sensusSurvei){
        this.isLoggedIn = isLoggedIn;
        this.status = status;
        this.sensusSurveiId = sensusSurvei;
        
        checkLogin(this.isLoggedIn);
        this.setMenuEnable(isLoggedIn, status);
    }
    
    public void checkLogin(boolean b){
        if(b){
            this.mainPanel.removeAll();
            this.mainPanel.add(new HomePanel(this));
            this.mainPanel.repaint();
            this.mainPanel.revalidate();
        }else{
            this.mainPanel.removeAll();
            this.mainPanel.add(new LoginPanel(this));
            this.mainPanel.repaint();
            this.mainPanel.revalidate();
        }
    }
    
    private void setMenuEnable(boolean b, int status){
        switch (status) {
            case 1:
                //admin
                this.btnMenuHome.setVisible(b);
                this.btnMenuEntri.setVisible(b);
                this.btnMenuValidasi.setVisible(b);
                this.btnMenuProgress.setVisible(b);
                this.btnMenuLogout.setVisible(b);
                break;
            case 2:
                //supervisor
                this.btnMenuHome.setVisible(b);
                this.btnMenuProgress.setVisible(b);
                this.btnMenuLogout.setVisible(b);
                break;
            case 3:
                //operator
                this.btnMenuHome.setVisible(b);
                this.btnMenuEntri.setVisible(b);
                this.btnMenuValidasi.setVisible(b);
                this.btnMenuLogout.setVisible(b);
                break;
            case 0:
                this.btnMenuHome.setVisible(b);
                this.btnMenuEntri.setVisible(b);
                this.btnMenuValidasi.setVisible(b);
                this.btnMenuProgress.setVisible(b);
                this.btnMenuLogout.setVisible(b);
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g){
                super.paintComponent(g);
                g.drawImage(new ImageIcon(ResourceImage.getResource(StringImage.BACKGROUND_IMG)).getImage(),0,0,null);
            }
        };
        headerPanel = new javax.swing.JPanel();
        btnMenuEntri = new javax.swing.JButton();
        btnMenuValidasi = new javax.swing.JButton();
        btnMenuProgress = new javax.swing.JButton();
        btnMenuLogout = new javax.swing.JButton();
        btnMenuHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setOpaque(false);
        mainPanel.setPreferredSize(new java.awt.Dimension(1024, 670));
        mainPanel.setLayout(new java.awt.CardLayout());
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        headerPanel.setBackground(new java.awt.Color(0, 102, 102));
        headerPanel.setPreferredSize(new java.awt.Dimension(1024, 54));

        btnMenuEntri.setBackground(new java.awt.Color(102, 102, 255));
        btnMenuEntri.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenuEntri.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuEntri.setText("Entri Mitra");
        btnMenuEntri.setBorderPainted(false);
        btnMenuEntri.setOpaque(true);
        btnMenuEntri.setSize(new java.awt.Dimension(97, 35));
        btnMenuEntri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuEntriActionPerformed(evt);
            }
        });

        btnMenuValidasi.setBackground(new java.awt.Color(102, 102, 255));
        btnMenuValidasi.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenuValidasi.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuValidasi.setText("Validasi Pegawai");
        btnMenuValidasi.setBorderPainted(false);
        btnMenuValidasi.setOpaque(true);
        btnMenuValidasi.setSize(new java.awt.Dimension(97, 35));
        btnMenuValidasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuValidasiActionPerformed(evt);
            }
        });

        btnMenuProgress.setBackground(new java.awt.Color(102, 102, 255));
        btnMenuProgress.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenuProgress.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuProgress.setText("Validasi Mitra");
        btnMenuProgress.setBorderPainted(false);
        btnMenuProgress.setOpaque(true);
        btnMenuProgress.setSize(new java.awt.Dimension(97, 35));
        btnMenuProgress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuProgressActionPerformed(evt);
            }
        });

        btnMenuLogout.setBackground(new java.awt.Color(255, 102, 102));
        btnMenuLogout.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenuLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuLogout.setText("Log Out");
        btnMenuLogout.setBorderPainted(false);
        btnMenuLogout.setOpaque(true);
        btnMenuLogout.setSize(new java.awt.Dimension(97, 35));
        btnMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLogoutActionPerformed(evt);
            }
        });

        btnMenuHome.setBackground(new java.awt.Color(255, 255, 255));
        btnMenuHome.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btnMenuHome.setForeground(new java.awt.Color(255, 255, 255));
        btnMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/go/bps/lampung/monitorentri/assets/home.png"))); // NOI18N
        btnMenuHome.setText("Home");
        btnMenuHome.setAlignmentY(0.0F);
        btnMenuHome.setBorderPainted(false);
        btnMenuHome.setContentAreaFilled(false);
        btnMenuHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenuHome.setPreferredSize(new java.awt.Dimension(35, 35));
        btnMenuHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuHomeActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Kendali Pengolahan versi 1.0.3");

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenuHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(btnMenuEntri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuProgress)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuValidasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 196, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMenuLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMenuEntri)
                    .addComponent(btnMenuValidasi)
                    .addComponent(btnMenuProgress)
                    .addComponent(btnMenuLogout)
                    .addComponent(btnMenuHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(13, 13, 13))
        );

        getContentPane().add(headerPanel, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuEntriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuEntriActionPerformed
        // TODO add your handling code here:
        this.mainPanel.removeAll();
        this.mainPanel.add(new EntrianPanel(this));
        this.mainPanel.repaint();
        this.mainPanel.revalidate();
    }//GEN-LAST:event_btnMenuEntriActionPerformed

    private void btnMenuValidasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuValidasiActionPerformed
        // TODO add your handling code here:
        this.mainPanel.removeAll();
        this.mainPanel.add(new ValidasiPanel(this));
        this.mainPanel.repaint();
        this.mainPanel.revalidate();
    }//GEN-LAST:event_btnMenuValidasiActionPerformed

    private void btnMenuProgressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuProgressActionPerformed
        // TODO add your handling code here:
        this.mainPanel.removeAll();
        this.mainPanel.add(new ValidasiMitraPanel(this));
        this.mainPanel.repaint();
        this.mainPanel.revalidate();
        this.setMenuEnable(true, this.status);
    }//GEN-LAST:event_btnMenuProgressActionPerformed

    private void btnMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLogoutActionPerformed
        // TODO add your handling code here:
        this.mainPanel.removeAll();
        this.mainPanel.add(new LoginPanel(this));
        this.mainPanel.repaint();
        this.mainPanel.revalidate();
        this.setMenuEnable(false, 0);
    }//GEN-LAST:event_btnMenuLogoutActionPerformed

    private void btnMenuHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuHomeActionPerformed
        // TODO add your handling code here:
        this.mainPanel.removeAll();
        this.mainPanel.add(new HomePanel(this));
        this.mainPanel.repaint();
        this.mainPanel.revalidate();
        this.setMenuEnable(true, this.status);
    }//GEN-LAST:event_btnMenuHomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuEntri;
    private javax.swing.JButton btnMenuHome;
    private javax.swing.JButton btnMenuLogout;
    private javax.swing.JButton btnMenuProgress;
    private javax.swing.JButton btnMenuValidasi;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
