/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.go.bps.lampung.monitorentri.ui;

/**
 *
 * @author ekoteguh
 */
public class MainFrame extends javax.swing.JFrame {

    String username, sensusSurveiId;
    boolean isLoggedIn = true;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        
        MainFrame.this.setSize(1024, 720);
        MainFrame.this.setLocationRelativeTo(null);
        MainFrame.this.setResizable(false);
        MainFrame.this.checkLogin(isLoggedIn);
    }
    
    public void setLogged(boolean isLoggedIn, String username, String sensusSurvei){
        this.isLoggedIn = isLoggedIn;
        this.username = username;
        this.sensusSurveiId = sensusSurvei;
    }
    
    public void checkLogin(boolean b){
        if(b){
            //MainFrame.this.mainPanel.remove(new LoginPanel(this));
            MainFrame.this.mainPanel.add(new EntrianPanel(this));
        }else{
            //MainFrame.this.mainPanel.remove(new EntrianPanel(this));
            MainFrame.this.mainPanel.add(new LoginPanel(this));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        headerPanel = new javax.swing.JPanel();
        menuEntri = new javax.swing.JLabel();
        menuValidasi = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        menuProgress = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setPreferredSize(new java.awt.Dimension(1024, 670));
        mainPanel.setLayout(new java.awt.BorderLayout());

        headerPanel.setBackground(new java.awt.Color(0, 102, 102));
        headerPanel.setPreferredSize(new java.awt.Dimension(1024, 54));

        menuEntri.setBackground(new java.awt.Color(0, 102, 255));
        menuEntri.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menuEntri.setForeground(new java.awt.Color(255, 255, 255));
        menuEntri.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuEntri.setText("Entri");
        menuEntri.setOpaque(true);
        menuEntri.setPreferredSize(new java.awt.Dimension(41, 30));
        menuEntri.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuEntriMouseClicked(evt);
            }
        });

        menuValidasi.setBackground(new java.awt.Color(0, 102, 255));
        menuValidasi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menuValidasi.setForeground(new java.awt.Color(255, 255, 255));
        menuValidasi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuValidasi.setText("Validasi");
        menuValidasi.setOpaque(true);
        menuValidasi.setPreferredSize(new java.awt.Dimension(68, 30));
        menuValidasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuValidasiMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Versi 1.0.0");

        menuProgress.setBackground(new java.awt.Color(0, 102, 255));
        menuProgress.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        menuProgress.setForeground(new java.awt.Color(255, 255, 255));
        menuProgress.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuProgress.setText("Progress");
        menuProgress.setOpaque(true);
        menuProgress.setPreferredSize(new java.awt.Dimension(78, 30));

        javax.swing.GroupLayout headerPanelLayout = new javax.swing.GroupLayout(headerPanel);
        headerPanel.setLayout(headerPanelLayout);
        headerPanelLayout.setHorizontalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuEntri, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuValidasi, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menuProgress, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        headerPanelLayout.setVerticalGroup(
            headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, headerPanelLayout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(headerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menuEntri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menuValidasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(menuProgress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(headerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(headerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuEntriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuEntriMouseClicked
        // TODO add your handling code here:
        MainFrame.this.mainPanel.add(new EntrianPanel(this));
    }//GEN-LAST:event_menuEntriMouseClicked

    private void menuValidasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuValidasiMouseClicked
        // TODO add your handling code here:
        MainFrame.this.mainPanel.add(new ValidasiPanel(this));
    }//GEN-LAST:event_menuValidasiMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel headerPanel;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel menuEntri;
    private javax.swing.JLabel menuProgress;
    private javax.swing.JLabel menuValidasi;
    // End of variables declaration//GEN-END:variables
}
