/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.go.bps.lampung.monitorentri.ui;

import id.go.bps.lampung.monitorentri.helper.DBProperty;
import java.awt.BorderLayout;
import java.awt.Dimension;
import javafx.application.Platform;
import javafx.collections.ObservableList;
import javafx.embed.swing.JFXPanel;
import javafx.scene.Group;
import javafx.scene.Node;
import javafx.scene.Scene;
import javafx.scene.layout.StackPane;
import javafx.scene.web.WebEngine;
import javafx.scene.web.WebView;

/**
 *
 * @author ekoteguh
 */
public class ProgressPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    MainFrame mainFrame;
    WebEngine webEngine;

    public ProgressPanel(MainFrame frame) {
        this.mainFrame = frame;
        initComponents();
        this.showBrowser();
    }

    private void showBrowser() {
        JFXPanel fXPanel = new JFXPanel();
        fXPanel.setPreferredSize(new Dimension(990, 600));
        this.panelChart.add(fXPanel, BorderLayout.CENTER);

        Platform.runLater(() -> {
            initFX(fXPanel);
            this.webEngine.reload();
        });
    }

    private void initFX(JFXPanel fxPanel) {
        // This method is invoked on the JavaFX thread
        Scene scene = createScene();
        fxPanel.setScene(scene);
    }

    private Scene createScene() {
        Group root = new Group();
        StackPane stackPane = new StackPane();
        Scene scene = new Scene(stackPane);
        
        WebView webView = new WebView();
        this.webEngine = webView.getEngine();
        this.webEngine.setJavaScriptEnabled(true);
        this.webEngine.load("http://" + DBProperty.getHost() + "/kendalientri");
        
        ObservableList<Node> children = stackPane.getChildren();
        children.add(webView);
        
        return (scene);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelChart = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 102, 0));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1024, 670));
        setLayout(new java.awt.BorderLayout());

        panelChart.setPreferredSize(new java.awt.Dimension(993, 605));
        panelChart.setLayout(new java.awt.BorderLayout());
        add(panelChart, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel panelChart;
    // End of variables declaration//GEN-END:variables
}
